healthkit = "Healthkit"

progressive_aqueduct = "Progressive Aqueducts Event"
progressive_heater = "Progressive Heater Core Event"
progressive_vent = "Progressive Ventilation Event"

module_missile = "Missile Module"
module_decoder = "Decoder Module"
module_repeater = "Repeater Module"
module_hopper = "Hopper Module"
module_spinjump = "Spin Jump Module"
module_coolant = "Coolant Module"
module_phase = "Phase Module"
module_bigshot = "Big Shot Module"

#Cartridge Locations
cartridge_1 = "Bark Palette Cartridge"
cartridge_2 = "Nicotine Palette Cartridge"
cartridge_3 = "Starboard Palette Cartridge"
cartridge_4 = "Coffee Stain Palette Cartridge"
cartridge_5 = "Virtual Cat Matcha Palette Cartridge"
cartridge_6 = "Port Palette Cartridge"
cartridge_7 = "Meowtrix Palette Cartridge"
cartridge_8 = "Goop Palette Cartridge"
cartridge_9 = "Urine Palette Cartridge"
cartridge_10 = "Tamagato Palette Cartridge"
cartridge_11 = "Gris Palette Cartridge"
cartridge_12 = "Chewed Gum Palette Cartridge"
cartridge_13 = "Swamp Matcha Palette Cartridge"
cartridge_14 = "Grape Palette Cartridge"