healthkit = "Healthkit"
cartridge = "Cartridge"

progressive_treadmill = "Treadmill Event"
progressive_hotboy = "Hotboy Event"
hottubes_event = "Hot Tubes Event"
progressive_vent = "Vent Button Event"

module_missile = "Missile Module"
module_decoder = "Decoder Module"
module_repeater = "Repeater Module"
module_hopper = "Hopper Module"
module_spinjump = "Spin Jump Module"
module_coolant = "Coolant Module"
module_phase = "Phase Module"
module_bigshot = "Big Shot Module"