healthkit_1 = "West Landing Site Healthkit"
healthkit_2 = "East Landing Site Healthkit"
healthkit_3 = "West Nexus Healthkit"
healthkit_4 = "East Nexus Healthkit"
healthkit_5 = "West Aquaducts Healthkit"
healthkit_6 = "East Aquaducts Healthkit"
healthkit_7 = "West Heater Healthkit"
healthkit_8 = "East Heater Healthkit"
healthkit_9 = "Ventilation Healthkit"
healthkit_10 = "Incubator Healthkit"

progressive_aqueduct_1 = "Aqueducts Event 1"
progressive_aqueduct_2 = "Aqueducts Event 2"
progressive_aqueduct_3 = "Aqueducts Event 3"

progressive_heater_1 = "Heater Core Event 1"
progressive_heater_2 = "Heater Core Event 2"
progressive_heater_3 = "Heater Core Event 3"

progressive_vent_1 = "Ventilation Event 1"
progressive_vent_2 = "Ventilation Event 2"
progressive_vent_3 = "Ventilation Event 3"

module_missile = "Missile Module"
module_decoder = "Decoder Module"
module_repeater = "Repeater Module"
module_hopper = "Hopper Module"
module_spinjump = "Spin Jump Module"
module_coolant = "Coolant Module"
module_phase = "Phase Module"
module_bigshot = "Big Shot Module"

#Cartridge Locations
cartridge_1 = "Bark Palette Cartridge"
cartridge_2 = "Nicotine Palette Cartridge"
cartridge_3 = "Starboard Palette Cartridge"
cartridge_4 = "Coffee Stain Palette Cartridge"
cartridge_5 = "Virtual Cat Matcha Palette Cartridge"
cartridge_6 = "Port Palette Cartridge"
cartridge_7 = "Meowtrix Palette Cartridge"
cartridge_8 = "Goop Palette Cartridge"
cartridge_9 = "Urine Palette Cartridge"
cartridge_10 = "Tamagato Palette Cartridge"
cartridge_11 = "Gris Palette Cartridge"
cartridge_12 = "Chewed Gum Palette Cartridge"
cartridge_13 = "Swamp Matcha Palette Cartridge"
cartridge_14 = "Grape Palette Cartridge"