# Healthkit Locations
healthkit_1 = "West Landing Site Healthkit"
healthkit_2 = "East Landing Site Healthkit"
healthkit_3 = "West Nexus Healthkit"
healthkit_4 = "East Nexus Healthkit"
healthkit_5 = "West Nexus Healthkit"
healthkit_6 = "East Nexus Healthkit"
healthkit_7 = "West Heater Healthkit"
healthkit_8 = "East Heater Healthkit"
healthkit_9 = "Ventilation Healthkit"
healthkit_10 = "Incubator Healthkit"

#Cartridge Locations
cartridge_1 = "Bark Palette Cartridge"
cartridge_2 = "Nicotine Palette Cartridge"
cartridge_3 = "Coffee Stain Palette Cartridge"
cartridge_4 = "Urine Palette Cartridge"
cartridge_5 = "Swamp Matcha Palette Cartridge"
cartridge_6 = "Port Palette Cartridge"
cartridge_7 = "Goop Palette Cartridge"
cartridge_8 = "Starboard Palette Cartridge"
cartridge_9 = "Virtualcat Palette Cartridge"
cartridge_10 = "Meowtrix Palette Cartridge"
cartridge_11 = "Chewed Gum Palette Cartridge"
cartridge_12 = "Gris Palette Cartridge"
cartridge_13 = "Grape Palette Cartridge"
cartridge_14 = "Tamagato Palette Cartridge"

#Module Locations
module_1 = "Missile Module Location"
module_2 = "Decoder Module Location"
module_3 = "Repeater Module Location"
module_4 = "Hopper Module Location"
module_5 = "Spin Jump Module Location"
module_6 = "Coolant Module Location"
module_7 = "Phase Module Location"
module_8 = "Big Shot Module Location"
